{
 "title": "Sample Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Counter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "prom_sample_counter", "legendFormat": "counter" }
   ]
  },
  {
   "title": "Gauge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 0 },
   "targets": [
    { "expr": "prom_sample_gauge" }
   ]
  },
  {
   "title": "Gauge",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "prom_sample_labeled_gauge", "legendFormat": "labeled_gauge={{id}}" },
    { "expr": "prom_sample_gauge", "legendFormat": "normal_gauge" }
   ]
  },
  {
   "title": "Histogram",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prom_sample_histogram_bucket[5m])) by (status_code) / sum(rate(prom_sample_histogram_count[5m])) by (status_code)"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prom_sample_summary{quantile=\"0.5\"}",
     "legendFormat": "status_code={{status_code}}"
    }
   ]
  },
  {
   "title": "200",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "prom_sample_histogram_count{status_code=\"200\"}"
    }
   ]
  },
  {
   "title": "400",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "prom_sample_histogram_count{status_code=\"400\"}"
    }
   ]
  },
  {
   "title": "403",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "prom_sample_histogram_count{status_code=\"403\"}"
    }
   ]
  },
  {
   "title": "404",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "prom_sample_histogram_count{status_code=\"404\"}"
    }
   ]
  },
  {
   "title": "500",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "prom_sample_histogram_count{status_code=\"500\"}"
    }
   ]
  },
  {
   "title": "Average duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prom_sample_histogram_sum / prom_sample_histogram_count",
     "legendFormat": "status_code={{status_code}}"
    }
   ]
  }
 ]
}