{
 "title": "Sample Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Counter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "prom_sample_counter" }
   ]
  },
  {
   "title": "Gauge",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "prom_sample_labeled_gauge" }
   ]
  },
  {
   "title": "Gauge",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 16, "y": 0 },
   "targets": [
    { "expr": "prom_sample_gauge" }
   ]
  },
  {
   "title": "Histogram",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "prom_sample_histogram_count" }
   ]
  },
  {
   "title": "Summary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "prom_sample_summary" }
   ]
  }
 ]
}